// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bllli/logto-management-api/models/components"
)

type AssertSamlRequest struct {
	// The unique identifier of the connector.
	ConnectorID string         `pathParam:"style=simple,explode=false,name=connectorId"`
	RequestBody map[string]any `request:"mediaType=application/json"`
}

func (o *AssertSamlRequest) GetConnectorID() string {
	if o == nil {
		return ""
	}
	return o.ConnectorID
}

func (o *AssertSamlRequest) GetRequestBody() map[string]any {
	if o == nil {
		return map[string]any{}
	}
	return o.RequestBody
}

type AssertSamlResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *AssertSamlResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
