// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bllli/logto-management-api/models/components"
)

type AssignOrganizationRolesToApplicationsRequestBody struct {
	// An array of application IDs to assign roles to.
	ApplicationIds []string `json:"applicationIds"`
	// An array of organization role IDs to assign to the applications.
	OrganizationRoleIds []string `json:"organizationRoleIds"`
}

func (o *AssignOrganizationRolesToApplicationsRequestBody) GetApplicationIds() []string {
	if o == nil {
		return []string{}
	}
	return o.ApplicationIds
}

func (o *AssignOrganizationRolesToApplicationsRequestBody) GetOrganizationRoleIds() []string {
	if o == nil {
		return []string{}
	}
	return o.OrganizationRoleIds
}

type AssignOrganizationRolesToApplicationsRequest struct {
	// The unique identifier of the organization.
	ID          string                                           `pathParam:"style=simple,explode=false,name=id"`
	RequestBody AssignOrganizationRolesToApplicationsRequestBody `request:"mediaType=application/json"`
}

func (o *AssignOrganizationRolesToApplicationsRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *AssignOrganizationRolesToApplicationsRequest) GetRequestBody() AssignOrganizationRolesToApplicationsRequestBody {
	if o == nil {
		return AssignOrganizationRolesToApplicationsRequestBody{}
	}
	return o.RequestBody
}

type AssignOrganizationRolesToApplicationsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *AssignOrganizationRolesToApplicationsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
