// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bllli/logto-management-api/models/components"
)

type CreateResourceScopeRequestBody struct {
	// The name of the scope. It should be unique for the resource.
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

func (o *CreateResourceScopeRequestBody) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateResourceScopeRequestBody) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

type CreateResourceScopeRequest struct {
	// The unique identifier of the resource.
	ResourceID  string                         `pathParam:"style=simple,explode=false,name=resourceId"`
	RequestBody CreateResourceScopeRequestBody `request:"mediaType=application/json"`
}

func (o *CreateResourceScopeRequest) GetResourceID() string {
	if o == nil {
		return ""
	}
	return o.ResourceID
}

func (o *CreateResourceScopeRequest) GetRequestBody() CreateResourceScopeRequestBody {
	if o == nil {
		return CreateResourceScopeRequestBody{}
	}
	return o.RequestBody
}

// CreateResourceScopeResponseBody - The created scope.
type CreateResourceScopeResponseBody struct {
	TenantID    string  `json:"tenantId"`
	ID          string  `json:"id"`
	ResourceID  string  `json:"resourceId"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	CreatedAt   float64 `json:"createdAt"`
}

func (o *CreateResourceScopeResponseBody) GetTenantID() string {
	if o == nil {
		return ""
	}
	return o.TenantID
}

func (o *CreateResourceScopeResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateResourceScopeResponseBody) GetResourceID() string {
	if o == nil {
		return ""
	}
	return o.ResourceID
}

func (o *CreateResourceScopeResponseBody) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateResourceScopeResponseBody) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CreateResourceScopeResponseBody) GetCreatedAt() float64 {
	if o == nil {
		return 0.0
	}
	return o.CreatedAt
}

type CreateResourceScopeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The created scope.
	Object *CreateResourceScopeResponseBody
}

func (o *CreateResourceScopeResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateResourceScopeResponse) GetObject() *CreateResourceScopeResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
