// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bllli/logto-management-api/models/components"
)

type CreateOrganizationRoleScopeRequestBody struct {
	// An array of organization scope IDs to be assigned. Existed scope IDs assignments will be ignored.
	OrganizationScopeIds []string `json:"organizationScopeIds"`
}

func (o *CreateOrganizationRoleScopeRequestBody) GetOrganizationScopeIds() []string {
	if o == nil {
		return []string{}
	}
	return o.OrganizationScopeIds
}

type CreateOrganizationRoleScopeRequest struct {
	// The unique identifier of the organization role.
	ID          string                                 `pathParam:"style=simple,explode=false,name=id"`
	RequestBody CreateOrganizationRoleScopeRequestBody `request:"mediaType=application/json"`
}

func (o *CreateOrganizationRoleScopeRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateOrganizationRoleScopeRequest) GetRequestBody() CreateOrganizationRoleScopeRequestBody {
	if o == nil {
		return CreateOrganizationRoleScopeRequestBody{}
	}
	return o.RequestBody
}

type CreateOrganizationRoleScopeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *CreateOrganizationRoleScopeResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
