// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bllli/logto-management-api/models/components"
)

type CreateOrganizationScopeRequest struct {
	TenantID *string `json:"tenantId,omitempty"`
	// The name of the organization scope. It must be unique within the organization template.
	Name string `json:"name"`
	// The description of the organization scope.
	Description *string `json:"description,omitempty"`
}

func (o *CreateOrganizationScopeRequest) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *CreateOrganizationScopeRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateOrganizationScopeRequest) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

// CreateOrganizationScopeResponseBody - The organization scope was created successfully.
type CreateOrganizationScopeResponseBody struct {
	TenantID    string  `json:"tenantId"`
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (o *CreateOrganizationScopeResponseBody) GetTenantID() string {
	if o == nil {
		return ""
	}
	return o.TenantID
}

func (o *CreateOrganizationScopeResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateOrganizationScopeResponseBody) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateOrganizationScopeResponseBody) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

type CreateOrganizationScopeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The organization scope was created successfully.
	Object *CreateOrganizationScopeResponseBody
}

func (o *CreateOrganizationScopeResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateOrganizationScopeResponse) GetObject() *CreateOrganizationScopeResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
