// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bllli/logto-management-api/models/components"
)

type DeleteSsoConnectorRequest struct {
	// The unique identifier of the sso connector.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeleteSsoConnectorRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type DeleteSsoConnectorResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeleteSsoConnectorResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
