// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/bllli/logto-management-api/models/components"
)

type TargetType string

const (
	TargetTypeUser TargetType = "User"
	TargetTypeApp  TargetType = "App"
)

func (e TargetType) ToPointer() *TargetType {
	return &e
}
func (e *TargetType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "User":
		fallthrough
	case "App":
		*e = TargetType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TargetType: %v", v)
	}
}

type DeleteSentinelActivitiesRequest struct {
	TargetType TargetType `json:"targetType"`
	Targets    []string   `json:"targets"`
}

func (o *DeleteSentinelActivitiesRequest) GetTargetType() TargetType {
	if o == nil {
		return TargetType("")
	}
	return o.TargetType
}

func (o *DeleteSentinelActivitiesRequest) GetTargets() []string {
	if o == nil {
		return []string{}
	}
	return o.Targets
}

type DeleteSentinelActivitiesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeleteSentinelActivitiesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
