// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bllli/logto-management-api/models/components"
)

type GetHasuraAuthRequest struct {
	Resource         string  `queryParam:"style=form,explode=true,name=resource"`
	UnauthorizedRole *string `queryParam:"style=form,explode=true,name=unauthorizedRole"`
}

func (o *GetHasuraAuthRequest) GetResource() string {
	if o == nil {
		return ""
	}
	return o.Resource
}

func (o *GetHasuraAuthRequest) GetUnauthorizedRole() *string {
	if o == nil {
		return nil
	}
	return o.UnauthorizedRole
}

// GetHasuraAuthResponseBody - The authenticated user claims in Hasura format. See [Hasura docs](https://hasura.io/docs/latest/auth/authentication/webhook/#webhook-response) for more information.
type GetHasuraAuthResponseBody struct {
	XHasuraUserID *string `json:"X-Hasura-User-Id,omitempty"`
	XHasuraRole   *string `json:"X-Hasura-Role,omitempty"`
}

func (o *GetHasuraAuthResponseBody) GetXHasuraUserID() *string {
	if o == nil {
		return nil
	}
	return o.XHasuraUserID
}

func (o *GetHasuraAuthResponseBody) GetXHasuraRole() *string {
	if o == nil {
		return nil
	}
	return o.XHasuraRole
}

type GetHasuraAuthResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The authenticated user claims in Hasura format. See [Hasura docs](https://hasura.io/docs/latest/auth/authentication/webhook/#webhook-response) for more information.
	Object *GetHasuraAuthResponseBody
}

func (o *GetHasuraAuthResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetHasuraAuthResponse) GetObject() *GetHasuraAuthResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
