// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bllli/logto-management-api/internal/utils"
	"github.com/bllli/logto-management-api/models/components"
)

type ListResourceScopesRequest struct {
	// The unique identifier of the resource.
	ResourceID string `pathParam:"style=simple,explode=false,name=resourceId"`
	// Page number (starts from 1).
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Entries per page.
	PageSize *int64 `default:"20" queryParam:"style=form,explode=true,name=page_size"`
	// Search query parameters.
	SearchParams map[string]string `queryParam:"style=form,explode=true,name=search_params"`
}

func (l ListResourceScopesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListResourceScopesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListResourceScopesRequest) GetResourceID() string {
	if o == nil {
		return ""
	}
	return o.ResourceID
}

func (o *ListResourceScopesRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListResourceScopesRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *ListResourceScopesRequest) GetSearchParams() map[string]string {
	if o == nil {
		return nil
	}
	return o.SearchParams
}

type ListResourceScopesResponseBody struct {
	TenantID    string  `json:"tenantId"`
	ID          string  `json:"id"`
	ResourceID  string  `json:"resourceId"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	CreatedAt   float64 `json:"createdAt"`
}

func (o *ListResourceScopesResponseBody) GetTenantID() string {
	if o == nil {
		return ""
	}
	return o.TenantID
}

func (o *ListResourceScopesResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ListResourceScopesResponseBody) GetResourceID() string {
	if o == nil {
		return ""
	}
	return o.ResourceID
}

func (o *ListResourceScopesResponseBody) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ListResourceScopesResponseBody) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *ListResourceScopesResponseBody) GetCreatedAt() float64 {
	if o == nil {
		return 0.0
	}
	return o.CreatedAt
}

type ListResourceScopesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// An array of scopes for the requested resource.
	ResponseBodies []ListResourceScopesResponseBody
}

func (o *ListResourceScopesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListResourceScopesResponse) GetResponseBodies() []ListResourceScopesResponseBody {
	if o == nil {
		return nil
	}
	return o.ResponseBodies
}
