// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bllli/logto-management-api/internal/utils"
	"github.com/bllli/logto-management-api/models/components"
)

type ListOrganizationJitEmailDomainsRequest struct {
	// The unique identifier of the organization.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Page number (starts from 1).
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Entries per page.
	PageSize *int64 `default:"20" queryParam:"style=form,explode=true,name=page_size"`
}

func (l ListOrganizationJitEmailDomainsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListOrganizationJitEmailDomainsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListOrganizationJitEmailDomainsRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ListOrganizationJitEmailDomainsRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListOrganizationJitEmailDomainsRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

type ListOrganizationJitEmailDomainsResponseBody struct {
	TenantID       string `json:"tenantId"`
	OrganizationID string `json:"organizationId"`
	EmailDomain    string `json:"emailDomain"`
}

func (o *ListOrganizationJitEmailDomainsResponseBody) GetTenantID() string {
	if o == nil {
		return ""
	}
	return o.TenantID
}

func (o *ListOrganizationJitEmailDomainsResponseBody) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

func (o *ListOrganizationJitEmailDomainsResponseBody) GetEmailDomain() string {
	if o == nil {
		return ""
	}
	return o.EmailDomain
}

type ListOrganizationJitEmailDomainsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A list of email domains.
	ResponseBodies []ListOrganizationJitEmailDomainsResponseBody
}

func (o *ListOrganizationJitEmailDomainsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListOrganizationJitEmailDomainsResponse) GetResponseBodies() []ListOrganizationJitEmailDomainsResponseBody {
	if o == nil {
		return nil
	}
	return o.ResponseBodies
}
