// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/bllli/logto-management-api/models/components"
)

type PostAPIInteractionVerificationWebauthnRegistrationRp struct {
	Name string  `json:"name"`
	ID   *string `json:"id,omitempty"`
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationRp) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationRp) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

type PostAPIInteractionVerificationWebauthnRegistrationUser struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	DisplayName string `json:"displayName"`
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationUser) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationUser) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationUser) GetDisplayName() string {
	if o == nil {
		return ""
	}
	return o.DisplayName
}

type PostAPIInteractionVerificationWebauthnRegistrationPubKeyCredParam struct {
	Type string  `json:"type"`
	Alg  float64 `json:"alg"`
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationPubKeyCredParam) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationPubKeyCredParam) GetAlg() float64 {
	if o == nil {
		return 0.0
	}
	return o.Alg
}

type PostAPIInteractionVerificationWebauthnRegistrationTransport string

const (
	PostAPIInteractionVerificationWebauthnRegistrationTransportUsb       PostAPIInteractionVerificationWebauthnRegistrationTransport = "usb"
	PostAPIInteractionVerificationWebauthnRegistrationTransportNfc       PostAPIInteractionVerificationWebauthnRegistrationTransport = "nfc"
	PostAPIInteractionVerificationWebauthnRegistrationTransportBle       PostAPIInteractionVerificationWebauthnRegistrationTransport = "ble"
	PostAPIInteractionVerificationWebauthnRegistrationTransportInternal  PostAPIInteractionVerificationWebauthnRegistrationTransport = "internal"
	PostAPIInteractionVerificationWebauthnRegistrationTransportCable     PostAPIInteractionVerificationWebauthnRegistrationTransport = "cable"
	PostAPIInteractionVerificationWebauthnRegistrationTransportHybrid    PostAPIInteractionVerificationWebauthnRegistrationTransport = "hybrid"
	PostAPIInteractionVerificationWebauthnRegistrationTransportSmartCard PostAPIInteractionVerificationWebauthnRegistrationTransport = "smart-card"
)

func (e PostAPIInteractionVerificationWebauthnRegistrationTransport) ToPointer() *PostAPIInteractionVerificationWebauthnRegistrationTransport {
	return &e
}
func (e *PostAPIInteractionVerificationWebauthnRegistrationTransport) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "usb":
		fallthrough
	case "nfc":
		fallthrough
	case "ble":
		fallthrough
	case "internal":
		fallthrough
	case "cable":
		fallthrough
	case "hybrid":
		fallthrough
	case "smart-card":
		*e = PostAPIInteractionVerificationWebauthnRegistrationTransport(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostAPIInteractionVerificationWebauthnRegistrationTransport: %v", v)
	}
}

type PostAPIInteractionVerificationWebauthnRegistrationExcludeCredential struct {
	Type       string                                                        `json:"type"`
	ID         string                                                        `json:"id"`
	Transports []PostAPIInteractionVerificationWebauthnRegistrationTransport `json:"transports,omitempty"`
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationExcludeCredential) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationExcludeCredential) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationExcludeCredential) GetTransports() []PostAPIInteractionVerificationWebauthnRegistrationTransport {
	if o == nil {
		return nil
	}
	return o.Transports
}

type PostAPIInteractionVerificationWebauthnRegistrationAuthenticatorAttachment string

const (
	PostAPIInteractionVerificationWebauthnRegistrationAuthenticatorAttachmentPlatform      PostAPIInteractionVerificationWebauthnRegistrationAuthenticatorAttachment = "platform"
	PostAPIInteractionVerificationWebauthnRegistrationAuthenticatorAttachmentCrossPlatform PostAPIInteractionVerificationWebauthnRegistrationAuthenticatorAttachment = "cross-platform"
)

func (e PostAPIInteractionVerificationWebauthnRegistrationAuthenticatorAttachment) ToPointer() *PostAPIInteractionVerificationWebauthnRegistrationAuthenticatorAttachment {
	return &e
}
func (e *PostAPIInteractionVerificationWebauthnRegistrationAuthenticatorAttachment) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "platform":
		fallthrough
	case "cross-platform":
		*e = PostAPIInteractionVerificationWebauthnRegistrationAuthenticatorAttachment(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostAPIInteractionVerificationWebauthnRegistrationAuthenticatorAttachment: %v", v)
	}
}

type PostAPIInteractionVerificationWebauthnRegistrationResidentKey string

const (
	PostAPIInteractionVerificationWebauthnRegistrationResidentKeyDiscouraged PostAPIInteractionVerificationWebauthnRegistrationResidentKey = "discouraged"
	PostAPIInteractionVerificationWebauthnRegistrationResidentKeyPreferred   PostAPIInteractionVerificationWebauthnRegistrationResidentKey = "preferred"
	PostAPIInteractionVerificationWebauthnRegistrationResidentKeyRequired    PostAPIInteractionVerificationWebauthnRegistrationResidentKey = "required"
)

func (e PostAPIInteractionVerificationWebauthnRegistrationResidentKey) ToPointer() *PostAPIInteractionVerificationWebauthnRegistrationResidentKey {
	return &e
}
func (e *PostAPIInteractionVerificationWebauthnRegistrationResidentKey) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "discouraged":
		fallthrough
	case "preferred":
		fallthrough
	case "required":
		*e = PostAPIInteractionVerificationWebauthnRegistrationResidentKey(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostAPIInteractionVerificationWebauthnRegistrationResidentKey: %v", v)
	}
}

type PostAPIInteractionVerificationWebauthnRegistrationUserVerification string

const (
	PostAPIInteractionVerificationWebauthnRegistrationUserVerificationRequired    PostAPIInteractionVerificationWebauthnRegistrationUserVerification = "required"
	PostAPIInteractionVerificationWebauthnRegistrationUserVerificationPreferred   PostAPIInteractionVerificationWebauthnRegistrationUserVerification = "preferred"
	PostAPIInteractionVerificationWebauthnRegistrationUserVerificationDiscouraged PostAPIInteractionVerificationWebauthnRegistrationUserVerification = "discouraged"
)

func (e PostAPIInteractionVerificationWebauthnRegistrationUserVerification) ToPointer() *PostAPIInteractionVerificationWebauthnRegistrationUserVerification {
	return &e
}
func (e *PostAPIInteractionVerificationWebauthnRegistrationUserVerification) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "required":
		fallthrough
	case "preferred":
		fallthrough
	case "discouraged":
		*e = PostAPIInteractionVerificationWebauthnRegistrationUserVerification(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostAPIInteractionVerificationWebauthnRegistrationUserVerification: %v", v)
	}
}

type PostAPIInteractionVerificationWebauthnRegistrationAuthenticatorSelection struct {
	AuthenticatorAttachment *PostAPIInteractionVerificationWebauthnRegistrationAuthenticatorAttachment `json:"authenticatorAttachment,omitempty"`
	RequireResidentKey      *bool                                                                      `json:"requireResidentKey,omitempty"`
	ResidentKey             *PostAPIInteractionVerificationWebauthnRegistrationResidentKey             `json:"residentKey,omitempty"`
	UserVerification        *PostAPIInteractionVerificationWebauthnRegistrationUserVerification        `json:"userVerification,omitempty"`
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationAuthenticatorSelection) GetAuthenticatorAttachment() *PostAPIInteractionVerificationWebauthnRegistrationAuthenticatorAttachment {
	if o == nil {
		return nil
	}
	return o.AuthenticatorAttachment
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationAuthenticatorSelection) GetRequireResidentKey() *bool {
	if o == nil {
		return nil
	}
	return o.RequireResidentKey
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationAuthenticatorSelection) GetResidentKey() *PostAPIInteractionVerificationWebauthnRegistrationResidentKey {
	if o == nil {
		return nil
	}
	return o.ResidentKey
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationAuthenticatorSelection) GetUserVerification() *PostAPIInteractionVerificationWebauthnRegistrationUserVerification {
	if o == nil {
		return nil
	}
	return o.UserVerification
}

type PostAPIInteractionVerificationWebauthnRegistrationAttestation string

const (
	PostAPIInteractionVerificationWebauthnRegistrationAttestationNone       PostAPIInteractionVerificationWebauthnRegistrationAttestation = "none"
	PostAPIInteractionVerificationWebauthnRegistrationAttestationIndirect   PostAPIInteractionVerificationWebauthnRegistrationAttestation = "indirect"
	PostAPIInteractionVerificationWebauthnRegistrationAttestationDirect     PostAPIInteractionVerificationWebauthnRegistrationAttestation = "direct"
	PostAPIInteractionVerificationWebauthnRegistrationAttestationEnterprise PostAPIInteractionVerificationWebauthnRegistrationAttestation = "enterprise"
)

func (e PostAPIInteractionVerificationWebauthnRegistrationAttestation) ToPointer() *PostAPIInteractionVerificationWebauthnRegistrationAttestation {
	return &e
}
func (e *PostAPIInteractionVerificationWebauthnRegistrationAttestation) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "none":
		fallthrough
	case "indirect":
		fallthrough
	case "direct":
		fallthrough
	case "enterprise":
		*e = PostAPIInteractionVerificationWebauthnRegistrationAttestation(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostAPIInteractionVerificationWebauthnRegistrationAttestation: %v", v)
	}
}

type PostAPIInteractionVerificationWebauthnRegistrationExtensions struct {
	Appid            *string `json:"appid,omitempty"`
	CredProps        *bool   `json:"credProps,omitempty"`
	HmacCreateSecret *bool   `json:"hmacCreateSecret,omitempty"`
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationExtensions) GetAppid() *string {
	if o == nil {
		return nil
	}
	return o.Appid
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationExtensions) GetCredProps() *bool {
	if o == nil {
		return nil
	}
	return o.CredProps
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationExtensions) GetHmacCreateSecret() *bool {
	if o == nil {
		return nil
	}
	return o.HmacCreateSecret
}

// PostAPIInteractionVerificationWebauthnRegistrationResponseBody - OK
type PostAPIInteractionVerificationWebauthnRegistrationResponseBody struct {
	Rp                     PostAPIInteractionVerificationWebauthnRegistrationRp                      `json:"rp"`
	User                   PostAPIInteractionVerificationWebauthnRegistrationUser                    `json:"user"`
	Challenge              string                                                                    `json:"challenge"`
	PubKeyCredParams       []PostAPIInteractionVerificationWebauthnRegistrationPubKeyCredParam       `json:"pubKeyCredParams"`
	Timeout                *float64                                                                  `json:"timeout,omitempty"`
	ExcludeCredentials     []PostAPIInteractionVerificationWebauthnRegistrationExcludeCredential     `json:"excludeCredentials,omitempty"`
	AuthenticatorSelection *PostAPIInteractionVerificationWebauthnRegistrationAuthenticatorSelection `json:"authenticatorSelection,omitempty"`
	Attestation            *PostAPIInteractionVerificationWebauthnRegistrationAttestation            `json:"attestation,omitempty"`
	Extensions             *PostAPIInteractionVerificationWebauthnRegistrationExtensions             `json:"extensions,omitempty"`
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationResponseBody) GetRp() PostAPIInteractionVerificationWebauthnRegistrationRp {
	if o == nil {
		return PostAPIInteractionVerificationWebauthnRegistrationRp{}
	}
	return o.Rp
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationResponseBody) GetUser() PostAPIInteractionVerificationWebauthnRegistrationUser {
	if o == nil {
		return PostAPIInteractionVerificationWebauthnRegistrationUser{}
	}
	return o.User
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationResponseBody) GetChallenge() string {
	if o == nil {
		return ""
	}
	return o.Challenge
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationResponseBody) GetPubKeyCredParams() []PostAPIInteractionVerificationWebauthnRegistrationPubKeyCredParam {
	if o == nil {
		return []PostAPIInteractionVerificationWebauthnRegistrationPubKeyCredParam{}
	}
	return o.PubKeyCredParams
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationResponseBody) GetTimeout() *float64 {
	if o == nil {
		return nil
	}
	return o.Timeout
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationResponseBody) GetExcludeCredentials() []PostAPIInteractionVerificationWebauthnRegistrationExcludeCredential {
	if o == nil {
		return nil
	}
	return o.ExcludeCredentials
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationResponseBody) GetAuthenticatorSelection() *PostAPIInteractionVerificationWebauthnRegistrationAuthenticatorSelection {
	if o == nil {
		return nil
	}
	return o.AuthenticatorSelection
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationResponseBody) GetAttestation() *PostAPIInteractionVerificationWebauthnRegistrationAttestation {
	if o == nil {
		return nil
	}
	return o.Attestation
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationResponseBody) GetExtensions() *PostAPIInteractionVerificationWebauthnRegistrationExtensions {
	if o == nil {
		return nil
	}
	return o.Extensions
}

type PostAPIInteractionVerificationWebauthnRegistrationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Object *PostAPIInteractionVerificationWebauthnRegistrationResponseBody
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostAPIInteractionVerificationWebauthnRegistrationResponse) GetObject() *PostAPIInteractionVerificationWebauthnRegistrationResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
