// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/bllli/logto-management-api/models/components"
)

type PutAPIInteractionEventEvent string

const (
	PutAPIInteractionEventEventSignIn         PutAPIInteractionEventEvent = "SignIn"
	PutAPIInteractionEventEventRegister       PutAPIInteractionEventEvent = "Register"
	PutAPIInteractionEventEventForgotPassword PutAPIInteractionEventEvent = "ForgotPassword"
)

func (e PutAPIInteractionEventEvent) ToPointer() *PutAPIInteractionEventEvent {
	return &e
}
func (e *PutAPIInteractionEventEvent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "SignIn":
		fallthrough
	case "Register":
		fallthrough
	case "ForgotPassword":
		*e = PutAPIInteractionEventEvent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PutAPIInteractionEventEvent: %v", v)
	}
}

type PutAPIInteractionEventRequest struct {
	Event PutAPIInteractionEventEvent `json:"event"`
}

func (o *PutAPIInteractionEventRequest) GetEvent() PutAPIInteractionEventEvent {
	if o == nil {
		return PutAPIInteractionEventEvent("")
	}
	return o.Event
}

type PutAPIInteractionEventResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *PutAPIInteractionEventResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
