// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bllli/logto-management-api/models/components"
)

type ReplaceOrganizationJitEmailDomainsRequestBody struct {
	// An array of email domains to replace existing email domains.
	EmailDomains []string `json:"emailDomains"`
}

func (o *ReplaceOrganizationJitEmailDomainsRequestBody) GetEmailDomains() []string {
	if o == nil {
		return []string{}
	}
	return o.EmailDomains
}

type ReplaceOrganizationJitEmailDomainsRequest struct {
	// The unique identifier of the organization.
	ID          string                                        `pathParam:"style=simple,explode=false,name=id"`
	RequestBody ReplaceOrganizationJitEmailDomainsRequestBody `request:"mediaType=application/json"`
}

func (o *ReplaceOrganizationJitEmailDomainsRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ReplaceOrganizationJitEmailDomainsRequest) GetRequestBody() ReplaceOrganizationJitEmailDomainsRequestBody {
	if o == nil {
		return ReplaceOrganizationJitEmailDomainsRequestBody{}
	}
	return o.RequestBody
}

type ReplaceOrganizationJitEmailDomainsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *ReplaceOrganizationJitEmailDomainsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
