// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bllli/logto-management-api/models/components"
)

// UpdateApplicationCustomDataRequestBody - An arbitrary JSON object.
type UpdateApplicationCustomDataRequestBody struct {
}

type UpdateApplicationCustomDataRequestRequest struct {
	// The unique identifier of the application.
	ApplicationID string                                 `pathParam:"style=simple,explode=false,name=applicationId"`
	RequestBody   UpdateApplicationCustomDataRequestBody `request:"mediaType=application/json"`
}

func (o *UpdateApplicationCustomDataRequestRequest) GetApplicationID() string {
	if o == nil {
		return ""
	}
	return o.ApplicationID
}

func (o *UpdateApplicationCustomDataRequestRequest) GetRequestBody() UpdateApplicationCustomDataRequestBody {
	if o == nil {
		return UpdateApplicationCustomDataRequestBody{}
	}
	return o.RequestBody
}

// UpdateApplicationCustomDataResponseBody - arbitrary
type UpdateApplicationCustomDataResponseBody struct {
}

type UpdateApplicationCustomDataResponseResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The updated custom data in JSON.
	Object *UpdateApplicationCustomDataResponseBody
}

func (o *UpdateApplicationCustomDataResponseResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateApplicationCustomDataResponseResponse) GetObject() *UpdateApplicationCustomDataResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
