// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bllli/logto-management-api/models/components"
)

type DevelopmentTenantMigrationNotificationRequest struct {
	IsPaidTenant bool     `json:"isPaidTenant"`
	Tag          string   `json:"tag"`
	ReadAt       *float64 `json:"readAt,omitempty"`
}

func (o *DevelopmentTenantMigrationNotificationRequest) GetIsPaidTenant() bool {
	if o == nil {
		return false
	}
	return o.IsPaidTenant
}

func (o *DevelopmentTenantMigrationNotificationRequest) GetTag() string {
	if o == nil {
		return ""
	}
	return o.Tag
}

func (o *DevelopmentTenantMigrationNotificationRequest) GetReadAt() *float64 {
	if o == nil {
		return nil
	}
	return o.ReadAt
}

type CheckedChargeNotificationRequest struct {
	Token               *bool `json:"token,omitempty"`
	APIResource         *bool `json:"apiResource,omitempty"`
	MachineToMachineApp *bool `json:"machineToMachineApp,omitempty"`
	TenantMember        *bool `json:"tenantMember,omitempty"`
}

func (o *CheckedChargeNotificationRequest) GetToken() *bool {
	if o == nil {
		return nil
	}
	return o.Token
}

func (o *CheckedChargeNotificationRequest) GetAPIResource() *bool {
	if o == nil {
		return nil
	}
	return o.APIResource
}

func (o *CheckedChargeNotificationRequest) GetMachineToMachineApp() *bool {
	if o == nil {
		return nil
	}
	return o.MachineToMachineApp
}

func (o *CheckedChargeNotificationRequest) GetTenantMember() *bool {
	if o == nil {
		return nil
	}
	return o.TenantMember
}

type UpdateAdminConsoleConfigRequest struct {
	SignInExperienceCustomized             *bool                                          `json:"signInExperienceCustomized,omitempty"`
	OrganizationCreated                    *bool                                          `json:"organizationCreated,omitempty"`
	DevelopmentTenantMigrationNotification *DevelopmentTenantMigrationNotificationRequest `json:"developmentTenantMigrationNotification,omitempty"`
	CheckedChargeNotification              *CheckedChargeNotificationRequest              `json:"checkedChargeNotification,omitempty"`
}

func (o *UpdateAdminConsoleConfigRequest) GetSignInExperienceCustomized() *bool {
	if o == nil {
		return nil
	}
	return o.SignInExperienceCustomized
}

func (o *UpdateAdminConsoleConfigRequest) GetOrganizationCreated() *bool {
	if o == nil {
		return nil
	}
	return o.OrganizationCreated
}

func (o *UpdateAdminConsoleConfigRequest) GetDevelopmentTenantMigrationNotification() *DevelopmentTenantMigrationNotificationRequest {
	if o == nil {
		return nil
	}
	return o.DevelopmentTenantMigrationNotification
}

func (o *UpdateAdminConsoleConfigRequest) GetCheckedChargeNotification() *CheckedChargeNotificationRequest {
	if o == nil {
		return nil
	}
	return o.CheckedChargeNotification
}

type UpdateAdminConsoleConfigDevelopmentTenantMigrationNotificationResponse struct {
	IsPaidTenant bool     `json:"isPaidTenant"`
	Tag          string   `json:"tag"`
	ReadAt       *float64 `json:"readAt,omitempty"`
}

func (o *UpdateAdminConsoleConfigDevelopmentTenantMigrationNotificationResponse) GetIsPaidTenant() bool {
	if o == nil {
		return false
	}
	return o.IsPaidTenant
}

func (o *UpdateAdminConsoleConfigDevelopmentTenantMigrationNotificationResponse) GetTag() string {
	if o == nil {
		return ""
	}
	return o.Tag
}

func (o *UpdateAdminConsoleConfigDevelopmentTenantMigrationNotificationResponse) GetReadAt() *float64 {
	if o == nil {
		return nil
	}
	return o.ReadAt
}

type UpdateAdminConsoleConfigCheckedChargeNotificationResponse struct {
	Token               *bool `json:"token,omitempty"`
	APIResource         *bool `json:"apiResource,omitempty"`
	MachineToMachineApp *bool `json:"machineToMachineApp,omitempty"`
	TenantMember        *bool `json:"tenantMember,omitempty"`
}

func (o *UpdateAdminConsoleConfigCheckedChargeNotificationResponse) GetToken() *bool {
	if o == nil {
		return nil
	}
	return o.Token
}

func (o *UpdateAdminConsoleConfigCheckedChargeNotificationResponse) GetAPIResource() *bool {
	if o == nil {
		return nil
	}
	return o.APIResource
}

func (o *UpdateAdminConsoleConfigCheckedChargeNotificationResponse) GetMachineToMachineApp() *bool {
	if o == nil {
		return nil
	}
	return o.MachineToMachineApp
}

func (o *UpdateAdminConsoleConfigCheckedChargeNotificationResponse) GetTenantMember() *bool {
	if o == nil {
		return nil
	}
	return o.TenantMember
}

// UpdateAdminConsoleConfigResponseBody - The updated configuration object.
type UpdateAdminConsoleConfigResponseBody struct {
	SignInExperienceCustomized             bool                                                                    `json:"signInExperienceCustomized"`
	OrganizationCreated                    bool                                                                    `json:"organizationCreated"`
	DevelopmentTenantMigrationNotification *UpdateAdminConsoleConfigDevelopmentTenantMigrationNotificationResponse `json:"developmentTenantMigrationNotification,omitempty"`
	CheckedChargeNotification              *UpdateAdminConsoleConfigCheckedChargeNotificationResponse              `json:"checkedChargeNotification,omitempty"`
}

func (o *UpdateAdminConsoleConfigResponseBody) GetSignInExperienceCustomized() bool {
	if o == nil {
		return false
	}
	return o.SignInExperienceCustomized
}

func (o *UpdateAdminConsoleConfigResponseBody) GetOrganizationCreated() bool {
	if o == nil {
		return false
	}
	return o.OrganizationCreated
}

func (o *UpdateAdminConsoleConfigResponseBody) GetDevelopmentTenantMigrationNotification() *UpdateAdminConsoleConfigDevelopmentTenantMigrationNotificationResponse {
	if o == nil {
		return nil
	}
	return o.DevelopmentTenantMigrationNotification
}

func (o *UpdateAdminConsoleConfigResponseBody) GetCheckedChargeNotification() *UpdateAdminConsoleConfigCheckedChargeNotificationResponse {
	if o == nil {
		return nil
	}
	return o.CheckedChargeNotification
}

type UpdateAdminConsoleConfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The updated configuration object.
	Object *UpdateAdminConsoleConfigResponseBody
}

func (o *UpdateAdminConsoleConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateAdminConsoleConfigResponse) GetObject() *UpdateAdminConsoleConfigResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
