// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bllli/logto-management-api/models/components"
)

type UpdateResourceIsDefaultRequestBody struct {
	// The updated value of the `isDefault` property.
	IsDefault bool `json:"isDefault"`
}

func (o *UpdateResourceIsDefaultRequestBody) GetIsDefault() bool {
	if o == nil {
		return false
	}
	return o.IsDefault
}

type UpdateResourceIsDefaultRequest struct {
	// The unique identifier of the resource.
	ID          string                             `pathParam:"style=simple,explode=false,name=id"`
	RequestBody UpdateResourceIsDefaultRequestBody `request:"mediaType=application/json"`
}

func (o *UpdateResourceIsDefaultRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateResourceIsDefaultRequest) GetRequestBody() UpdateResourceIsDefaultRequestBody {
	if o == nil {
		return UpdateResourceIsDefaultRequestBody{}
	}
	return o.RequestBody
}

// UpdateResourceIsDefaultResponseBody - The updated resource.
type UpdateResourceIsDefaultResponseBody struct {
	TenantID       string  `json:"tenantId"`
	ID             string  `json:"id"`
	Name           string  `json:"name"`
	Indicator      string  `json:"indicator"`
	IsDefault      bool    `json:"isDefault"`
	AccessTokenTTL float64 `json:"accessTokenTtl"`
}

func (o *UpdateResourceIsDefaultResponseBody) GetTenantID() string {
	if o == nil {
		return ""
	}
	return o.TenantID
}

func (o *UpdateResourceIsDefaultResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateResourceIsDefaultResponseBody) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *UpdateResourceIsDefaultResponseBody) GetIndicator() string {
	if o == nil {
		return ""
	}
	return o.Indicator
}

func (o *UpdateResourceIsDefaultResponseBody) GetIsDefault() bool {
	if o == nil {
		return false
	}
	return o.IsDefault
}

func (o *UpdateResourceIsDefaultResponseBody) GetAccessTokenTTL() float64 {
	if o == nil {
		return 0.0
	}
	return o.AccessTokenTTL
}

type UpdateResourceIsDefaultResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The updated resource.
	Object *UpdateResourceIsDefaultResponseBody
}

func (o *UpdateResourceIsDefaultResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateResourceIsDefaultResponse) GetObject() *UpdateResourceIsDefaultResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
