// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/bllli/logto-management-api/models/components"
)

// VerifyVerificationBySocialConnectorData - A json object constructed from the url query params returned by the social platform. Typically it contains `code`, `state` and `redirectUri` fields.
type VerifyVerificationBySocialConnectorData struct {
}

type VerifyVerificationBySocialRequest struct {
	// A json object constructed from the url query params returned by the social platform. Typically it contains `code`, `state` and `redirectUri` fields.
	ConnectorData        VerifyVerificationBySocialConnectorData `json:"connectorData"`
	VerificationRecordID string                                  `json:"verificationRecordId"`
	// The verification ID of the SocialVerification record.
	VerificationID any `json:"verificationId,omitempty"`
}

func (o *VerifyVerificationBySocialRequest) GetConnectorData() VerifyVerificationBySocialConnectorData {
	if o == nil {
		return VerifyVerificationBySocialConnectorData{}
	}
	return o.ConnectorData
}

func (o *VerifyVerificationBySocialRequest) GetVerificationRecordID() string {
	if o == nil {
		return ""
	}
	return o.VerificationRecordID
}

func (o *VerifyVerificationBySocialRequest) GetVerificationID() any {
	if o == nil {
		return nil
	}
	return o.VerificationID
}

// VerifyVerificationBySocialResponseBody - The social verification record has been successfully verified and the user information has been saved.
type VerifyVerificationBySocialResponseBody struct {
	VerificationRecordID string `json:"verificationRecordId"`
}

func (o *VerifyVerificationBySocialResponseBody) GetVerificationRecordID() string {
	if o == nil {
		return ""
	}
	return o.VerificationRecordID
}

type VerifyVerificationBySocialResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The social verification record has been successfully verified and the user information has been saved.
	Object *VerifyVerificationBySocialResponseBody
}

func (o *VerifyVerificationBySocialResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *VerifyVerificationBySocialResponse) GetObject() *VerifyVerificationBySocialResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
