// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/bllli/logto-management-api/models/components"
)

type VerifyVerificationCodeVerificationType string

const (
	VerifyVerificationCodeVerificationTypeEmail VerifyVerificationCodeVerificationType = "email"
	VerifyVerificationCodeVerificationTypePhone VerifyVerificationCodeVerificationType = "phone"
)

func (e VerifyVerificationCodeVerificationType) ToPointer() *VerifyVerificationCodeVerificationType {
	return &e
}
func (e *VerifyVerificationCodeVerificationType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "email":
		fallthrough
	case "phone":
		*e = VerifyVerificationCodeVerificationType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VerifyVerificationCodeVerificationType: %v", v)
	}
}

// VerifyVerificationCodeVerificationIdentifier - The identifier (email address or phone number) to verify the code against. Must match the identifier used to send the verification code.
type VerifyVerificationCodeVerificationIdentifier struct {
	Type  VerifyVerificationCodeVerificationType `json:"type"`
	Value string                                 `json:"value"`
}

func (o *VerifyVerificationCodeVerificationIdentifier) GetType() VerifyVerificationCodeVerificationType {
	if o == nil {
		return VerifyVerificationCodeVerificationType("")
	}
	return o.Type
}

func (o *VerifyVerificationCodeVerificationIdentifier) GetValue() string {
	if o == nil {
		return ""
	}
	return o.Value
}

type VerifyVerificationCodeVerificationRequest struct {
	// The identifier (email address or phone number) to verify the code against. Must match the identifier used to send the verification code.
	Identifier VerifyVerificationCodeVerificationIdentifier `json:"identifier"`
	// The verification ID of the CodeVerification record.
	VerificationID string `json:"verificationId"`
	// The verification code to be verified.
	Code string `json:"code"`
}

func (o *VerifyVerificationCodeVerificationRequest) GetIdentifier() VerifyVerificationCodeVerificationIdentifier {
	if o == nil {
		return VerifyVerificationCodeVerificationIdentifier{}
	}
	return o.Identifier
}

func (o *VerifyVerificationCodeVerificationRequest) GetVerificationID() string {
	if o == nil {
		return ""
	}
	return o.VerificationID
}

func (o *VerifyVerificationCodeVerificationRequest) GetCode() string {
	if o == nil {
		return ""
	}
	return o.Code
}

// VerifyVerificationCodeVerificationResponseBody - The verification code was successfully verified.
type VerifyVerificationCodeVerificationResponseBody struct {
	// The unique ID of the verification record. Required for user identification via the `Identification` API or to bind the identifier to the user's account via the `Profile` API.
	VerificationID string `json:"verificationId"`
}

func (o *VerifyVerificationCodeVerificationResponseBody) GetVerificationID() string {
	if o == nil {
		return ""
	}
	return o.VerificationID
}

type VerifyVerificationCodeVerificationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The verification code was successfully verified.
	Object *VerifyVerificationCodeVerificationResponseBody
}

func (o *VerifyVerificationCodeVerificationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *VerifyVerificationCodeVerificationResponse) GetObject() *VerifyVerificationCodeVerificationResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
