workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Logto API references:
        inputs:
            - location: ../logto-openapi-source.json
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/wtf/temp/logto-api-references
targets:
    logto-management-api:
        target: go
        source: Logto API references
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/wtf/temp/logto-api-references-go-code-samples
            labelOverride:
                fixedValue: Go (SDK)
            blocking: false
